# name of main workflow
name: Production

# This workflow will build and deploy your app to Vercel when a push is made to the main branch
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

# This will filter branches to only run on the main branch
on:
  push:
    branches:
      - main

# This will make jobs on your pipelines
jobs:

  Test:
    runs-on: ubuntu-latest
    steps:

        - uses: actions/checkout@v3

        - uses: actions/setup-node@v3
          with:
            node-version: 18
        
        - run: npm ci
        - run: npm run test:prod

  Deploy-Production:
    runs-on: ubuntu-latest
    steps:
    
        - uses: actions/checkout@v3

        - name: Installation Vercel
          run: npm i -g vercel

        - name: Pull vercel environment
          run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

        - name: Build project
          run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

        - name: Deploy project
          run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}